# -*- coding: utf-8 -*-
"""alpha-beta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0PfkQOftM5LrB2lN3E0aKmFNfInauJm
"""

N = 8
board = [-1] * N

def is_safe(row, col):
    for i in range(row):
        if board[i] == col or abs(board[i] - col) == abs(i - row):
            return False
    return True

def solve(row):
    if row == N:
        return True

    for col in range(N):
        if is_safe(row, col):
            board[row] = col
            if solve(row + 1):
                return True
            board[row] = -1

    return False

def print_board():
    print("\n 8-Queens Solution:\n")
    for i in range(N):
        for j in range(N):
            if board[i] == j:
                print("Q", end=" ")
            else:
                print(".", end=" ")
        print()

if solve(0):
    print_board()
else:
    print(" No solution found")