# -*- coding: utf-8 -*-
"""bfs ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_R4pNMBarOn3LFHegDLZeD4R7tMMW96
"""

import copy
import random
import time
import math
from collections import defaultdict
import heapq

# 2. BEST-FIRST SEARCH (using heuristic = conflicts contributed by each column)


def heuristic_conflict_by_col(state, col):
    """If state has queen at col, count conflicts for that queen. If None, return min possible conflicts."""
    r = state[col]
    if r is None:
        # compute minimal conflicts if placed optimally (we return 0..7)
        min_conf = 8
        for row in range(8):
            c = 0
            for c2 in range(8):
                if c2 == col:
                    continue
                if state[c2] is None:
                    continue
                if state[c2] == row or abs(state[c2]-row) == abs(c2 - col):
                    c += 1
            if c < min_conf:
                min_conf = c
        return min_conf
    else:
        c = 0
        for c2 in range(8):
            if c2 == col:
                continue
            if state[c2] is None:
                continue
            if state[c2] == r or abs(state[c2]-r) == abs(c2 - col):
                c += 1
        return c

def best_first_8queens(state=None):
    """Recursive best-first: choose column with highest current conflicts (to fix it) and try rows ordered by least conflicts."""
    if state is None:
        state = [None]*8
    # if all assigned check
    if all(v is not None for v in state):
        return state if conflicts(state) == 0 else None

    # choose column with max heuristic (most problematic)
    best_col = None
    best_score = -1
    for col in range(8):
        if state[col] is None:
            # estimate by checking how many placements would conflict given current fixed queens
            # or choose column with largest number of attacked squares by existing queens
            score = 0
            for row in range(8):
                if not is_safe(state, col, row):
                    score += 1
            if score > best_score:
                best_score = score
                best_col = col

    if best_col is None:
        return None

    # try rows in order of least conflicts after placement
    row_scores = []
    for row in range(8):
        if is_safe(state, best_col, row):
            # compute conflicts introduced
            temp = state[:]
            temp[best_col] = row
            row_scores.append((conflicts(temp), row))
    row_scores.sort()  # ascending conflicts

    for sc, row in row_scores:
        state[best_col] = row
        res = best_first_8queens(state)
        if res is not None:
            return res
        state[best_col] = None

    return None

def test_best_first():
    print("\n" + "="*50)
    print("ALGORITHM 2: BEST-FIRST SEARCH")
    print("="*50)
    start = time.time()
    sol = best_first_8queens()
    end = time.time()
    if sol:
        print("✓ Solution found (Best-First):")
        print_state(sol)
        print("Conflicts:", conflicts(sol))
    else:
        print("✗ No solution found (Best-First)")
    print(f"Time: {end-start:.4f}s")
    return sol