# -*- coding: utf-8 -*-
"""dls .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_R4pNMBarOn3LFHegDLZeD4R7tMMW96
"""

class Node:
    def __init__(self, state: list, parent=None, depth: int = 0):
        self.state = state
        self.parent = parent
        self.depth = depth

def print_board(state: list):
    N = len(state)
    print("\n" + "=" * (N * 4 + 7))
    print("|| 8-Queens Board ||")
    print("=" * (N * 4 + 7))
    for r in range(N):
        row_str = " | "
        for c in range(N):
            if state[r] == c:
                row_str += " Q |"
            else:
                row_str += " . |"
        print(row_str)
        print(" " + "-" * (N * 4 + 3))

def is_safe(state: list, row: int, col: int) -> bool:
    for r in range(row):
        c = state[r]
        if c == col or abs(c - col) == abs(r - row):
            return False
    return True

def DLS(node: Node, limit: int) -> Node or None:
    if node.depth == 8:
        return node

    if node.depth == limit:
        return None

    current_row = node.depth

    for col in range(8):
        if is_safe(node.state, current_row, col):
            new_state = node.state.copy()
            new_state[current_row] = col

            child = Node(new_state, node, node.depth + 1)

            result = DLS(child, limit)

            if result is not None:
                return result

    return None

# --- Execution ---

start_state = [-1] * 8
start_node = Node(start_state, None, 0)

LIMIT = 8

print(f"--- Starting Depth-Limited Search (DLS) for 8-Queens with limit = {LIMIT} ---")

solution_node = DLS(start_node, LIMIT)

if solution_node:
    print("\nSolution Found Successfully!")

    print_board(solution_node.state)

    print("\nQueen Positions (Row: Column):")
    for r, c in enumerate(solution_node.state):
        print(f"Queen in Row {r}: Column {c}")

else:
    print(f"\nNo solution found within the depth limit of {LIMIT}.")