# -*- coding: utf-8 -*-
"""genetic .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0PfkQOftM5LrB2lN3E0aKmFNfInauJm
"""

import random
import math

ROWS = 10
COLS = 10


maze = [[0]*COLS for _ in range(ROWS)]
maze[5][3] = maze[5][4] = maze[5][5] = 1

start = (0, 0)
goal = (9, 9)


moves = [
    (0, 1),
    (1, 0),
    (0, -1),
    (-1, 0)
]

CHR_LEN = 50
POP_SIZE = 100
MUTATION_RATE = 0.05



def calc_fitness(genes):
    x, y = start

    for g in genes:
        dx, dy = moves[g]
        nx, ny = x + dx, y + dy

        if 0 <= nx < ROWS and 0 <= ny < COLS and maze[nx][ny] == 0:
            x, y = nx, ny


    dist = abs(x - goal[0]) + abs(y - goal[1])

    return 1 / (dist + 1)


def random_chromosome():
    genes = [random.randint(0, 3) for _ in range(CHR_LEN)]
    fit = calc_fitness(genes)
    return {"genes": genes, "fitness": fit}



def select_parent(pop):
    total = sum(c["fitness"] for c in pop)
    r = random.uniform(0, total)
    s = 0
    for c in pop:
        s += c["fitness"]
        if s >= r:
            return c
    return pop[-1]

def crossover(a, b):
    point = random.randint(0, CHR_LEN - 1)
    child_genes = a["genes"][:point] + b["genes"][point:]
    return {"genes": child_genes, "fitness": calc_fitness(child_genes)}


# Mutation
def mutate(c):
    for i in range(CHR_LEN):
        if random.random() < MUTATION_RATE:
            c["genes"][i] = random.randint(0, 3)
    c["fitness"] = calc_fitness(c["genes"])


population = [random_chromosome() for _ in range(POP_SIZE)]

for generation in range(1, 301):


    population.sort(key=lambda c: c["fitness"], reverse=True)

    print(f"Generation {generation} | Best fitness = {population[0]['fitness']:.4f}")


    if population[0]["fitness"] > 0.5:
        print("\n✔ FOUND A GOOD PATH!")
        break

    new_population = []


    new_population.append(population[0])


    while len(new_population) < POP_SIZE:
        p1 = select_parent(population)
        p2 = select_parent(population)

        child = crossover(p1, p2)
        mutate(child)

        new_population.append(child)

    population = new_population


best = population[0]
print("\nBest Path Genes:")
print(best["genes"])
print("Fitness:", best["fitness"])