# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMUTldCYcePifYvYyg9N4l7RcjILvrfT
"""

import random

def random_state():
    return [random.randint(0,7) for _ in range(8)]


def calculate_attacks(state):
    attacks = 0
    for i in range(8):
        for j in range(i+1, 8):
            if state[i] == state[j] or abs(state[i]-state[j]) == abs(i-j):
                attacks += 1
    return attacks


def hill_climbing():
    state = random_state()
    current_attacks = calculate_attacks(state)

    while True:
        best_state = state[:]
        best_attacks = current_attacks

        for col in range(8):
            for row in range(8):
                if state[col] != row:
                    new_state = state[:]
                    new_state[col] = row
                    new_attacks = calculate_attacks(new_state)

                    if new_attacks < best_attacks:
                        best_state = new_state
                        best_attacks = new_attacks

        if best_attacks >= current_attacks:
            return state, current_attacks

        state = best_state
        current_attacks = best_attacks

solution, attacks = hill_climbing()
print("Solution:", solution)
print("Attacks:", attacks)