# -*- coding: utf-8 -*-
"""mini max .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_R4pNMBarOn3LFHegDLZeD4R7tMMW96
"""

import math
import random

GOAL = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 0]]

def copy_board(b):
    return [row[:] for row in b]

def print_board(b):
    for r in b:
        print(' '.join(str(x) if x else ' ' for x in r))
    print()

def find_empty(b):
    for i in range(3):
        for j in range(3):
            if b[i][j] == 0:
                return i, j

def get_neighbors(b):
    i, j = find_empty(b)
    moves = []
    for di, dj in [(-1,0), (1,0), (0,-1), (0,1)]:
        ni, nj = i+di, j+dj
        if 0 <= ni < 3 and 0 <= nj < 3:
            nb = copy_board(b)
            nb[i][j], nb[ni][nj] = nb[ni][nj], nb[i][j]
            moves.append(nb)
    return moves

def manhattan(b):
    d = 0
    for r in range(3):
        for c in range(3):
            v = b[r][c]
            if v:
                tr, tc = (v-1)//3, (v-1)%3
                d += abs(r-tr) + abs(c-tc)
    return d

def is_goal(b):
    return b == GOAL

def evaluate(b):
    return -manhattan(b)

def minimax(b, depth, is_max, max_d=4):
    if depth == max_d or is_goal(b):
        return evaluate(b)
    children = get_neighbors(b)
    if not children:
        return evaluate(b)
    if is_max:
        best = -math.inf
        for nb in children:
            best = max(best, minimax(nb, depth+1, False, max_d))
        return best
    else:
        best = math.inf
        for nb in children:
            best = min(best, minimax(nb, depth+1, True, max_d))
        return best

def best_move(b, is_x, max_d=4):
    moves = get_neighbors(b)
    if not moves:
        return None
    best_score = -math.inf if is_x else math.inf
    best_b = moves[0]
    for nb in moves:
        score = minimax(nb, 1, not is_x, max_d)
        if (is_x and score > best_score) or (not is_x and score < best_score):
            best_score, best_b = score, nb
    return best_b

def shuffle_board():
    b = copy_board(GOAL)
    for _ in range(30):
        nb = get_neighbors(b)
        b = random.choice(nb)
    return b

def play():
    print("🎮 Minimax 8-Puzzle (You=X=solver, AI=O=scrambler)")
    board = shuffle_board()
    turn_x = True

    while not is_goal(board):
        print_board(board)
        print(f"Dist: {manhattan(board)} | {'Your' if turn_x else 'AI'} turn")

        if turn_x:
            r, c = find_empty(board)
            opts, dirs = [], [(-1,0,'w'), (1,0,'s'), (0,-1,'a'), (0,1,'d')]
            for dr, dc, key in dirs:
                if 0 <= r+dr < 3 and 0 <= c+dc < 3:
                    opts.append((dr,dc,key))
            keys = '/'.join(k for _,_,k in opts)
            while True:
                m = input(f"Move empty ({keys}): ").strip()
                for dr,dc,key in opts:
                    if m == key:
                        nr, nc = r+dr, c+dc
                        board[r][c], board[nr][nc] = board[nr][nc], board[r][c]
                        break
                else:
                    print("Invalid"); continue
                break
        else:
            print("AI thinking...")
            nxt = best_move(board, False)
            if nxt:
                board = nxt
            else:
                break

        if is_goal(board):
            print_board(board)
            print("🎉 You reached the goal!")
            return

        turn_x = not turn_x

if __name__ == "__main__":
    play()